### ISSUE TITLE
build/install failures due to yanked crate and also with Rust 1.53.0

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#21]
Our CI job just started failing to run `cargo install cargo-generate-rpm --version 0.4.0`. This has been working fine until now. It fails due to a yanked aesni crate version, see https://github.com/NLnetLabs/routinator/runs/3171059667#step:9:17:

```
Caused by:
  failed to select a version for the requirement `aesni = "^0.7"`
  candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
```

Running with `--locked` fails for a different reason:

```
cargo install cargo-generate-rpm --version 0.4.0 --locked
    Updating crates.io index
  Installing cargo-generate-rpm v0.4.0
warning: package `aes-soft v0.4.0` in Cargo.lock is yanked in registry `crates.io`, consider running without --locked
warning: package `aesni v0.7.0` in Cargo.lock is yanked in registry `crates.io`, consider running without --locked
   Compiling autocfg v1.0.1
...
   Compiling rand_core v0.5.1
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lexical-core-0.7.4/src/atof/algorithm/bhcomp.rs:62:24
   |
62 |     let bytes = bits / Limb::BITS;
   |                        ^^^^^^^^^^ expected `usize`, found `u32`
```

**Works with Rust older than 1.53.0:**

One final note: Both my local machine and our CI build both used Rust 1.53.0. When I tried `cargo build` locally using Rust 1.47.0 and Rust 1.52.0, both succeeded!

In a clean Docker Ubuntu 18:04 container the following worked for me:

```
# rustup toolchain install 1.52.0
# cargo +1.52.0 install cargo-generate-rpm --version 0.4.0 --locked
```

**Comment by cat-in-136** [comment]
@ximon18 Could you please try with #23 ? In my environment on latest Rust, #23 resolves this issue.

**Comment by Fensteer** [comment]
Your PR fixes the problem thanks !

**Comment by ximon18** [comment]
@cat-in-136: Apologies for the delay in responding, I was out on vacation. Looks good to me:

```
$ docker run --rm -it rust:1.54 bash -c 'rustc -V && cargo install --git https://github.com/cat-in-136/cargo-generate-rpm --branch fix-build-fail-rust-1-53 --locked'
...
rustc 1.54.0 (a178d0322 2021-07-26)
...
   Installed package `cargo-generate-rpm v0.4.0 (https://github.com/cat-in-136/cargo-generate-rpm?branch=fix-build-fail-rust-1-53#6682a762)` (executable `cargo-generate-rpm`)
```

And:
```
$ docker run --rm -it rust:1.53 bash -c 'rustc -V && cargo install --git https://github.com/cat-in-136/cargo-generate-rpm --branch fix-build-fail-rust-1-53 --locked'
...
rustc 1.53.0 (53cb7b09b 2021-06-17)
...
   Installed package `cargo-generate-rpm v0.4.0 (https://github.com/cat-in-136/cargo-generate-rpm?branch=fix-build-fail-rust-1-53#6682a762)` (executable `cargo-generate-rpm`)
```

And:
```
$ docker run --rm -it rust:1.52 bash -c 'rustc -V && cargo install --git https://github.com/cat-in-136/cargo-generate-rpm --branch fix-build-fail-rust-1-53 --locked'
...
rustc 1.52.1 (9bc8c42bb 2021-05-09)
...
   Installed package `cargo-generate-rpm v0.4.0 (https://github.com/cat-in-136/cargo-generate-rpm?branch=fix-build-fail-rust-1-53#6682a762)` (executable `cargo-generate-rpm`)
```
